version : "3.8"
services :
  event:
    image : abdullah77044/event_new:v3
    container_name : event-container
    ports :
      - "9000:9000"
    restart : always
    networks:
      - event
networks:
  event:
